### ISSUE TITLE
No Window Shows up

### ISSUE THREAD

**Issue by mcgarrah** [ermaccer/FableMenu#1]
Attempted to try this out...

Extracted files to "C:\Program Files (x86)\Steam\steamapps\common\Fable Anniversary\Binaries\Win32" assuming that was the right place.

Tried to open with "~" and changed from controller to keyboard input as a test.

I must be missing something simple.

**Comment by ermaccer** [comment]
Are you sure you downloaded the correct version?

Anniversary version is here: https://github.com/ermaccer/FableMenuAnniversary (should've probably made a branch but would be confusing to do releases).

**Comment by mcgarrah** [comment]
No I was on the wrong version. I'll test it shortly.

**Comment by mcgarrah** [comment]
Awesome tool. Worked perfect once on the right version. Still learning all the functionality.
